-- Organizations and OrganizationSettings

CREATE TABLE "Organizations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Slug" character varying(100) NOT NULL,
    "InviteCode" character varying(10) NOT NULL,
    "LogoUrl" character varying(500),
    "Description" character varying(1000),
    "Address" character varying(300),
    "Phone" character varying(20),
    "Email" character varying(100),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt" timestamp with time zone,
    "IsActive" boolean NOT NULL DEFAULT true,
    CONSTRAINT "PK_Organizations" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Organizations_Slug" ON "Organizations" ("Slug");
CREATE UNIQUE INDEX "IX_Organizations_InviteCode" ON "Organizations" ("InviteCode");
CREATE INDEX "IX_Organizations_IsActive" ON "Organizations" ("IsActive");

CREATE TABLE "OrganizationSettings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" integer NOT NULL,
    "EnableWhatsAppNotifications" boolean NOT NULL DEFAULT true,
    "ReminderDaysBefore" integer NOT NULL DEFAULT 2,
    "MinimumMembersPerSchedule" integer NOT NULL DEFAULT 4,
    "MaximumMembersPerSchedule" integer NOT NULL DEFAULT 8,
    "MinimumDaysBetweenParticipation" integer NOT NULL DEFAULT 7,
    "ServiceTypesJson" character varying(2000) NOT NULL DEFAULT '[\"Culto Domingo Manhã\", \"Culto Domingo Noite\", \"Quarta-feira\"]',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_OrganizationSettings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrganizationSettings_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_OrganizationSettings_OrganizationId" ON "OrganizationSettings" ("OrganizationId");
