-- Roles, Members, OrganizationMembers, MemberRoles

CREATE TABLE "Role" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" integer,
    "Name" character varying(50) NOT NULL,
    "Category" character varying(50) NOT NULL DEFAULT 'Instrumento',
    "Icon" character varying(50),
    "DisplayOrder" integer NOT NULL DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT true,
    CONSTRAINT "PK_Role" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Role_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Role_OrganizationId_Name" ON "Role" ("OrganizationId", "Name");

CREATE TABLE "Members" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" integer NOT NULL,
    "UserId" text,
    "Name" character varying(100) NOT NULL,
    "Instrument" character varying(50),
    "Phone" character varying(20) NOT NULL DEFAULT '',
    "Email" character varying(100),
    "PhotoUrl" character varying(500),
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt" timestamp with time zone,
    "ParticipationCount" integer NOT NULL DEFAULT 0,
    "LastParticipationDate" timestamp with time zone,
    CONSTRAINT "PK_Members" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Members_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Members_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_Members_Name" ON "Members" ("Name");
CREATE INDEX "IX_Members_OrganizationId" ON "Members" ("OrganizationId");
CREATE INDEX "IX_Members_IsActive" ON "Members" ("IsActive");
CREATE INDEX "IX_Members_OrganizationId_UserId" ON "Members" ("OrganizationId", "UserId");

CREATE TABLE "OrganizationMembers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" integer NOT NULL,
    "UserId" text NOT NULL DEFAULT '',
    "Role" integer NOT NULL DEFAULT 1,
    "JoinedAt" timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "IsActive" boolean NOT NULL DEFAULT true,
    "MemberId" integer,
    CONSTRAINT "PK_OrganizationMembers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrganizationMembers_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrganizationMembers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrganizationMembers_Members_MemberId" FOREIGN KEY ("MemberId") REFERENCES "Members" ("Id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX "IX_OrganizationMembers_OrganizationId_UserId" ON "OrganizationMembers" ("OrganizationId", "UserId");
CREATE INDEX "IX_OrganizationMembers_UserId" ON "OrganizationMembers" ("UserId");

CREATE TABLE "MemberRoles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MemberId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    "IsPrimary" boolean NOT NULL DEFAULT false,
    "SkillLevel" integer NOT NULL DEFAULT 3,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    CONSTRAINT "PK_MemberRoles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MemberRoles_Members_MemberId" FOREIGN KEY ("MemberId") REFERENCES "Members" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MemberRoles_Role_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Role" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_MemberRoles_MemberId_RoleId" ON "MemberRoles" ("MemberId", "RoleId");
