-- Schedules, ScheduleMembers, ScheduleHistories

CREATE TABLE "Schedules" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "ServiceType" character varying(100) NOT NULL,
    "Description" character varying(500),
    "Status" integer NOT NULL DEFAULT 0,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" character varying(100),
    CONSTRAINT "PK_Schedules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Schedules_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Schedules_Date" ON "Schedules" ("Date");
CREATE INDEX "IX_Schedules_Status" ON "Schedules" ("Status");
CREATE INDEX "IX_Schedules_OrganizationId" ON "Schedules" ("OrganizationId");
CREATE INDEX "IX_Schedules_Date_ServiceType" ON "Schedules" ("Date", "ServiceType");

CREATE TABLE "ScheduleMembers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ScheduleId" integer NOT NULL,
    "MemberId" integer NOT NULL,
    "NotificationSent" boolean NOT NULL DEFAULT false,
    "NotificationSentAt" timestamp with time zone,
    "ConfirmedPresence" boolean,
    "ConfirmedAt" timestamp with time zone,
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    CONSTRAINT "PK_ScheduleMembers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ScheduleMembers_Schedules_ScheduleId" FOREIGN KEY ("ScheduleId") REFERENCES "Schedules" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ScheduleMembers_Members_MemberId" FOREIGN KEY ("MemberId") REFERENCES "Members" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_ScheduleMembers_ScheduleId_MemberId" ON "ScheduleMembers" ("ScheduleId", "MemberId");

CREATE TABLE "ScheduleHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ScheduleId" integer NOT NULL,
    "Action" character varying(50) NOT NULL,
    "Description" character varying(1000),
    "OldValue" text,
    "NewValue" text,
    "ChangedBy" character varying(100),
    "ChangedAt" timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    CONSTRAINT "PK_ScheduleHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ScheduleHistories_Schedules_ScheduleId" FOREIGN KEY ("ScheduleId") REFERENCES "Schedules" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ScheduleHistories_ScheduleId" ON "ScheduleHistories" ("ScheduleId");
CREATE INDEX "IX_ScheduleHistories_ChangedAt" ON "ScheduleHistories" ("ChangedAt");
