-- Songs and ScheduleSongs

CREATE TABLE "Songs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" integer NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Artist" character varying(200),
    "Key" character varying(50),
    "Tempo" character varying(20),
    "Category" character varying(50),
    "SpotifyUrl" character varying(500),
    "YouTubeUrl" character varying(500),
    "ChordsUrl" character varying(500),
    "Notes" character varying(2000),
    "Lyrics" character varying(2000),
    "TimesUsed" integer NOT NULL DEFAULT 0,
    "LastUsedDate" timestamp with time zone,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Songs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Songs_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Songs_OrganizationId" ON "Songs" ("OrganizationId");
CREATE INDEX "IX_Songs_Title" ON "Songs" ("Title");
CREATE INDEX "IX_Songs_Category" ON "Songs" ("Category");
CREATE INDEX "IX_Songs_IsActive" ON "Songs" ("IsActive");
CREATE INDEX "IX_Songs_OrganizationId_Title" ON "Songs" ("OrganizationId", "Title");

CREATE TABLE "ScheduleSongs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ScheduleId" integer NOT NULL,
    "SongId" integer NOT NULL,
    "Order" integer NOT NULL DEFAULT 0,
    "CustomKey" character varying(50),
    "Notes" character varying(500),
    "DurationMinutes" integer,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    CONSTRAINT "PK_ScheduleSongs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ScheduleSongs_Schedules_ScheduleId" FOREIGN KEY ("ScheduleId") REFERENCES "Schedules" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ScheduleSongs_Songs_SongId" FOREIGN KEY ("SongId") REFERENCES "Songs" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ScheduleSongs_ScheduleId" ON "ScheduleSongs" ("ScheduleId");
CREATE INDEX "IX_ScheduleSongs_SongId" ON "ScheduleSongs" ("SongId");
CREATE INDEX "IX_ScheduleSongs_ScheduleId_Order" ON "ScheduleSongs" ("ScheduleId", "Order");
