-- Availabilities and MessageTemplates

CREATE TABLE "Availabilities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" integer NOT NULL,
    "MemberId" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "IsAvailable" boolean NOT NULL DEFAULT true,
    "Notes" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Availabilities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Availabilities_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Availabilities_Members_MemberId" FOREIGN KEY ("MemberId") REFERENCES "Members" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Availabilities_Date" ON "Availabilities" ("Date");
CREATE INDEX "IX_Availabilities_OrganizationId" ON "Availabilities" ("OrganizationId");
CREATE UNIQUE INDEX "IX_Availabilities_MemberId_Date" ON "Availabilities" ("MemberId", "Date");

CREATE TABLE "MessageTemplates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Type" character varying(50) NOT NULL,
    "Template" character varying(2000) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_MessageTemplates" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_MessageTemplates_Type" ON "MessageTemplates" ("Type");
CREATE INDEX "IX_MessageTemplates_IsActive" ON "MessageTemplates" ("IsActive");
